stages:
  - Build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Build:
  stage: Build
  services:
    - registry
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - /kaniko/executor --insecure --context=$CI_PROJECT_DIR/kaniko  --dockerfile="$CI_PROJECT_DIR/kaniko/deploy/Dockerfile_debug" --destination=registry:5000/kaniko
